### PR TITLE
add github actions

### PR DESCRIPTION
**Pull request by lspgn**
Removes .travis-ci.yml and only covers build.
Test to come soon.

### CODE REVIEW

**Comment by massimocandela** [comment]
It could be that for the tests the pidfile error is related to https://github.com/nttgin/BGPalerter/issues/447
What OS uses GitHub actions?

**Comment by lspgn** [comment]
@massimocandela ubuntu

**Comment by massimocandela** [comment]
Thanks @lspgn!

Please, add your name in the contributors inside the AUTHORS file!!

**Comment by massimocandela** [comment]
Thanks @lspgn, since this PR doesn't involve any source code file, I'm planning to merge this into release so we can use the github actions already for the next patch release

**Pull request merged**
