### PR TITLE
add reportMatrix module

### PR DESCRIPTION
**Pull request by nickbouwhuis**
Added the reportMatrix module and documentation for it. 

Matrix requires messages to include a `txId` (as can be read in the Matrix documentation [here](https://spec.matrix.org/v1.5/client-server-api/#sending-events-to-a-room)) and thus the reportHTTP module cannot be used.

### CODE REVIEW

**Comment by massimocandela** [comment]
Hi @nickbouwhuis,

Thanks for this contribution and for adding yourself to the friends file! I'm going to add a few comments of review.

**Comment by massimocandela** [comment]
As you can see, all minor things :)
I can merge this for the next release (which will go out soon)

**Comment by nickbouwhuis** [comment]
> As you can see, all minor things :) I can merge this for the next release (which will go out soon)

Where did you add these comments? I'm guessing I am missing something :sweat_smile:

**Review by massimocandela — CHANGES_REQUESTED** [review]

**Comment by massimocandela** [comment]
> Where did you add these comments? I'm guessing I am missing something 😅

I think there is a final step after adding the comments that says "require changes" that I forgot. Are you able to see them now?

**Comment by massimocandela** [comment]
Thanks a lot for the contribution. I will merge this into the new release.

**Comment by massimocandela** [comment]
I just realized that probably the transaction Id generated in the constructor is not good enough. According to the documentation, the transaction id is used to avoid duplicated calls. Hence, it should be generated before every call. Am I reading this wrong? Anyway, I will patch it.

**Comment by massimocandela** [comment]
Patched. Please, use this https://github.com/nttgin/BGPalerter/releases/tag/v1.32.0 in your installation.

**Comment by nickbouwhuis** [comment]
> I just realized that probably the transaction Id generated in the constructor is not good enough. According to the documentation, the transaction id is used to avoid duplicated calls. Hence, it should be generated before every call. Am I reading this wrong? Anyway, I will patch it.

Yes. That is correct. My bad. I only tested it with `-it`. The transaction ID needs to be unique with every message.

**Comment by massimocandela** [comment]
Np, patched. Please, run the latest binary for some days and let me know if you experience any issue.

**Pull request merged**
