### PR TITLE
- added reporting to Telegram messenger

### PR DESCRIPTION
**Pull request by denisix**

### CODE REVIEW

**Comment by massimocandela** [comment]
Hi @denisix ,

Thanks for the contribution!
I think we should try to implement this as a configuration of reportHTTP. If not possible, we should at least create it as a class which extends reportHTTP (see reportSlack).

Additional things missing:
- support for user groups;
- documentation.

Ciao,
Massimo

**Comment by denisix** [comment]
Hi Massimo,

Thanks for your notes!
I will check regarding reportHTTP and update documentation soon.

Ciao,
Denys

**Comment by massimocandela** [comment]
Hi @denisix,

I implemented [here](https://github.com/nttgin/BGPalerter/commit/4fdd3540dbfd4533c5ba5ce07c8cd6e15cdb091e) the reportTelegram module with `reportHTTP` and support for user groups.

I run it for a bit and it looks working reliably. Let me know what you think (note: the configuration in config.yml is a bit different).

Thanks!

Ciao,
Massimo

**Comment by denisix** [comment]
Hi @massimocandela,

Thank you for updates, I will check.

**Pull request closed without merging**
