### PR TITLE
proxy support

### PR DESCRIPTION
**Pull request by massimocandela**
PR replacing #155 .Due to the commits done for testing Travis in GitHub, this PR will be squashed.

### CODE REVIEW

**Comment by massimocandela** [comment]
We also need to add the documentation:
* the httpProxy param in config.yml;
* the noProxy option for all the components;
* the -x option in generate prefixes;

**Comment by fdomain** [comment]
I can't push my changes directly to this repo (no access rights). I've pushed my commits to our fork here: https://github.com/criteo-forks/BGPalerter/commits/criteo-forks/dev

Should I re-submit another PR ?

**Comment by massimocandela** [comment]
No, thanks, I will merge them.

**Comment by massimocandela** [comment]
Thanks for your work (and sorry for the multiple branches). I think we are good to go. The only thing I think it is missing is to "block" outgoing traffic during the proxy test. On the other side, if the proxy is set but not configured properly the app fails and doesn't work so the test fails anyway. I think this is not a blocking point and we can merge this right now.

**Comment by fdomain** [comment]
I was thinking about the same point, the proxy test is partial compared to the main one. We are not testing and checking that all modules are going through the proxy.
I don't have a precise idea of how we could perform this, however here are some suggestions :
- watch all requests received by anyproxy and raised an error if a request has not been seen by anyproxy (but implies to run anyproxy as an npm module, and it doesn't seem trivial).
- filter in Travis by allowing only HTTP proxy to go to the Internet. I don't know how we could segment these two services (proxy and BGPalerter) from a network aspect in Travis, maybe we could accomplish this with the use of docker.

Anyway, I guess it's a good start. If you wish, we can test the pre-release in our environment and give you feedback. And thank you very much for the refactoring, the code looks much better than my first attempt.

**Comment by massimocandela** [comment]
Testing in your environment would be great. Could you tell me if you run the source code, the binary, or docker? So I can provide you with the fastest way to deploy the dev version.

**Comment by fdomain** [comment]
The binary for Linux would be perfect.

**Comment by massimocandela** [comment]
Easy version: download [this](https://github.com/nttgin/BGPalerter/files/4683842/bgpalerter-linux-x64.zip) (zipped due to GitHub restrictions on attached file types, unzip it)

To compile it yourself, do:
```bash
git clone git@github.com:nttgin/BGPalerter.git
git checkout dev
npm run build
```
The compiled version will be in `bin/`. More info [here](https://github.com/nttgin/BGPalerter/blob/master/docs/installation.md#running-bgpalerter-from-the-source-code) and [here](https://github.com/nttgin/BGPalerter/blob/master/docs/develop.md).


Since the latest release was some days ago, the next pre-release will be in some weeks. I hope this can help you in the meanwhile.

**Pull request merged**
