### PR TITLE
New reporter module for Alerta

### PR DESCRIPTION
**Pull request by mirceaulinic**
Adding a new reporter module largely inspired by the existing
``reportSlack`` to report events in Alerta (https://alerta.io/) via the
HTTP API.

### CODE REVIEW

**Comment by massimocandela** [comment]
It looks good, the only question I have: the report (in `_getResourceText`) should not be configurable from the config.yml (and a default one instead defined in the code)?

See https://github.com/nttgin/BGPalerter/blob/dev/src/reports/reportSyslog.js
And https://github.com/nttgin/BGPalerter/blob/master/config.yml.example#L114 (line 114) to understand what I mean.

Anyway, thank you for your contribution! Appreciated.

**Comment by mirceaulinic** [comment]
> It looks good, the only question I have: the report (in _getResourceText) should not be configurable from the config.yml (and a default one instead defined in the code)?

Oh, very good idea!

**Comment by massimocandela** [comment]
Ready to merge. Please, commit something in AUTHORS file, under the section 'CONTRIBUTORS' in the format:
`Name Surname, Company, email(optional)`

This is not mandatory ofc, just if you would like to be there.

**Comment by mirceaulinic** [comment]
Alright, added. :-)

**Pull request merged**
