### PR TITLE
Fix configuration parsing to allow api vrpProvider (avoid overriding …

### PR DESCRIPTION
**Pull request by wibisono**
I suppose this is one way to fix the issue reported here:
https://github.com/nttgin/BGPalerter/issues/1005

### CODE REVIEW

**Comment by massimocandela** [comment]
I pushed a fix in dev for this. The overriding was happening because "api" was not recognized as a valid value. Let me know in the ticket if everything now works for you.

**Comment by wibisono** [comment]
> I pushed a fix in dev for this. The overriding was happening because "api" was not recognized as a valid value. Let me know in the ticket if everything now works for you.

Thanks, btw just noticed that the fix has API as the first value. There might still be issues later on if people put random vrpProvider, and instead of going back to default RPKI client, API becomes the default now. 

But for what I need this is already working :)

**Comment by massimocandela** [comment]
hey @wibisono, Immediately after pushing I realised the same and fixed it in the next commit: https://github.com/nttgin/BGPalerter/commit/02a39bd3c8792cccec9d51bdce0b74342ce22ef7 (and cleaned https://github.com/nttgin/BGPalerter/commit/f2491ecd6890c00e312993d6d2886e4ceb976677)

**Comment by wibisono** [comment]
Great, thank you for the fix & quick response :)

**Pull request closed without merging**
