### PR TITLE
Added: docker-compose examples

### PR DESCRIPTION
**Pull request by GoliathLabs**
Hello,
I've added proper docker-compose examples for those who prefer to dock via compose.

The docker-compose.yml in the root of this git is the most basic one. The others that expose the port or add the healthcheck have been added to the corresponding sections in the installation documentation.

Feel free to leave some feedback 😄

### CODE REVIEW

**Comment by massimocandela** [comment]
Hi @GoliathLabs,

thank you for the PR!
I'm not a docker expert, my feedback is:
* I would remove the `docker-compose.yml` file and leave only the description in the doc as an alternative option to the docker command (mostly to reduce maintenance on my side and to avoid comments about "should we use compose for a single container?");
* I would improve the doc telling all the basic steps; e.g., "You can also use docker-compose for that:" can be replaced with "Alternatively, you can use docker-compose. Create a file named docker-compose.yml with the following content:" and after add something like "after do docker-compose up". The same for the other more complex composition. After you edit the doc, please verify that following the steps leads to a functioning composition.

**Comment by GoliathLabs** [comment]
@massimocandela we use the docker-compose with the healthcheck. We also tried the version without healthcheck and everything works fine :)

**Comment by GoliathLabs** [comment]
@massimocandela how do you push to docker hub? Do you build the image manually on your machine or do you have a CI somewhere else?

**Comment by massimocandela** [comment]
Thanks for this PR! Feel free to add your company at [here](https://github.com/nttgin/BGPalerter/blob/dev/docs/friends.md)

About your question: we have configured automated builds in docket hub on branches dev, main, and on version tags.

**Pull request merged**
