### PR TITLE
add proxy support

### LINKED ISSUE #19: add proxy support to connectorRIS
It may be required to run in an environment without direct access to the internet. The Websocket library suggests that this is possible 
https://github.com/websockets/ws#how-to-connect-via-a-proxy

using https-proxy-agent available here
https://github.com/TooTallNate/node-https-proxy-agent

It may also be useful to support proxy of other connections like those used by generate to download prefixes from RIPEstat.

### PR DESCRIPTION
**Pull request by fdomain**
add proxy support to WebSocket and HTTP(s) requests, based on environment variables `http_proxy` or `https_proxy`.

resolve #19 
I'm not sure that's the right approach, so your inputs are welcome.

### CODE REVIEW

**Comment by massimocandela** [comment]
Hi fdomain,

Thanks a lot for the contribution, which is always appreciated.

I tried in the past to solve #19 and I abandoned the mission because in my opinion adding proxy support introduces more headaches than good things.
The reason for this can be summarised with: 
* It introduces changes everywhere in the code, which have to be maintained and tested;
* Each module introduced (past and future) has to support this feature (e.g. like in your code, each module, including third-party ones, is forced to use your ad-hoc "axiosInstance" instead of a generic fetch library);
* It's more complicated to automatically test such feature (maybe we can use http://anyproxy.io/en/ in Travis). Additionally, if something breaks (maybe with a specific proxy) I will have to provide some minimum support/help.

Said that, let's try to work together on this:

* All configuration parameters have to be stored in config.yml. Since such parameters are global among the various modules, I would put them in a `httpProxy` dictionary. E.g.
```yaml
  httpProxy:
    host: 127.0.0.1
    port: 9000
    auth:
      username: something
      password: somethingElse
```
* I think we should support authentication.
* What if we declare the agent in `env.js` and we share it among the components?
* Automated tests are needed.
* Documentation is needed


Thanks again for this. I will keep reviewing the PR as soon as you push new things.

Ciao,
Massimo

**Comment by fdomain** [comment]
Hi Massimo,

Thank you very much for your answer.
I agree this is not a trivial task to add proxy support.

- as you suggested, I'll initialize the agent in `env.js`, based on yaml config file, and export it to other components.
Then each module will simply have to adapt Axios config (or any other library) when class constructor is called to be compliant with the proxy feature. e.g.
```JavaScript
    constructor(name, params, env) {
        axios.defaults.httpsAgent = env.agent;
    }
    ...
    axios(
      // axios request inheriting of httpsAgent
    )
```
- a `noProxy` parameter applied per unit (connector/reporter) could also be useful. Users may want to do not proxy their requests to internal apps. This parameter would have the precedence on the global proxy parameter. e.g.
```yaml
reports:
  - file: reportAlerta
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration
    params:
      noProxy: true
```
```JavaScript
        if (!this.params.noProxy) {
            axios.defaults.agent = env.agent;
        }
```
- the ad-hoc command `generate-prefixes` doesn't rely on configuration file, so I propose to add a new argument `--hp / --http-proxy` where you can specify which proxy to use.
e.g. `--hp http://<username>:<password>@<proxy_url>`
- regarding automated tests, I'll have to dig into this a bit more as it requires to spawn 
a HTTP proxy server (as anyproxy). Shouldn't be complicated though.

Don't hesitate to share your feeling about what I said above, I'll push new commits in coming days.

Thanks,
Florian

**Comment by nielsdenotter** [comment]
It would be great if proxy support can be achieved in bgpalerter. Also in our environment lot of management systems run behind a proxy. Though I understand your comments about complexity. Niels.

**Comment by massimocandela** [comment]
I'm open to it. I think the plan described by @fdomain in the last comment is doable.
I'm planning to work on such feature as soon as I have a moment. Contributions are welcome.

**Comment by nielsdenotter** [comment]
> I'm open to it. I think the plan described by @fdomain in the last comment is doable.
> I'm planning to work on such feature as soon as I have a moment. Contributions are welcome.

Least I can do is to test it in our environment. But if there is a base for adding this proxy functionality to connector/reporter I can propose changes for eg Slack (which is what we use).

**Comment by fdomain** [comment]
I worked a bit on it, but I was struggling with the testing part. I'll try to work on it soon when I have a moment.

**Comment by fdomain** [comment]
Hi @massimocandela 
I updated my PR according the plan we discussed above.
I still have to update the documentation.

**Comment by massimocandela** [comment]
Thanks, I'll look into it asap!

**Comment by massimocandela** [comment]
I merged this PR in the branch `criteo-forks/dev`. This branch is up to date with 1.25.0 and includes all your changes plus some variations I introduced. If we manage to solve a few issues with the tests, it will go out in 1.26.0.

The tests need to be fixed:
- We need to test both with and without proxy;
- I would like to exclude anyproxy from the dev dependencies, I was looking into starting an ad-hoc process directly in Travis CI, but it needs further investigation.
- I successfully used an external public proxy for the tests. Maybe this is a viable solution fto avoid anyproxy.

**Comment by fdomain** [comment]
Thanks, I'll have a look asap.

I agree that anyproxy brings a lot of dependencies, but I'm not sure it's better to use a public proxy that could come down anytime (tests may become red because the public proxy went down). Spawn an ad-hoc process in Travis CI seems nice, are you thinking about installing and starting an anyproxy server from Travis ? After some investigations, it looks doable by using `before_install:` or `install:` in `.travis.yml` file, and then call a bash script launching an anyproxy from the command line `anyproxy --port 8001`.

**Comment by massimocandela** [comment]
I agree with you on the possibility of the public proxy going down. What I meant with public was more in the line of "external" proxy, so to spawn an external proxy for testing (or maybe to use a pool of public one).
I'm definitely going for the Travis CI as first option, I'm looking into it.

**Comment by massimocandela** [comment]
I'm working in this branch: https://github.com/nttgin/BGPalerter/tree/travis-proxy

**Comment by massimocandela** [comment]
I merged `travis-proxy` back into `criteo-forks:dev`.
I created another PR [here](https://github.com/nttgin/BGPalerter/pull/234) (for some reason I was not able to merge back into this pull request).

We need the documentation as described in a previous comment.
Also, if you would like, add your name as a contributor in the authors file. To contribute, please clone directly this repo and use the `criteo-forks:dev` branch.

I added the anyproxy installation and execution in a separated script so it is not in the dependencies of the project. I created a test inside tests/proxy_tests to be performed through the proxy. Such test can be executed with `npm run test-proxy. The test runs reliably. Travis runs both (with and without proxy).

**Comment by massimocandela** [comment]
Closing this PR, moving to https://github.com/nttgin/BGPalerter/pull/234

**Pull request closed without merging**
