### PR TITLE
Update linux-service.md

### PR DESCRIPTION
**Pull request by jcoeder**
Showing users how to create a cron for automatic updates.  Perhaps there is a way to extract the current version and append that instead of the date.

### CODE REVIEW

**Comment by massimocandela** [comment]
Hi @jcoeder,

I tried to think other solutions where we detect for example if there is another release or not (using github apis).
But all of them involving installing other dependencies. 

I was thinking, what if instead of downloading and renaming the old version, we can first download the new version with a temporary name e.g. 

* `wget -O bgpalerter-linux-x64.tmp https://github.com/nttgin/BGPalerter/releases/latest/download/bgpalerter-linux-x64'
* check if the old version and the new version are the same 

```bash
v1=$(./bgpalerter-macos-x64 -v)
v2=$(./bgpalerter-macos-x64.tmp -v)
if [$v1 != $v2]; then
   mv bgpalerter-macos-x64 "bgpalerter-macos-x64-${v1}"
   mv bgpalerter-macos-x64.tmp bgpalerter-macos-x64
make executable
restart
etc
```

What do you think? In this way the process would be restarted only if necessary.

Let me know.

**Comment by jcoeder** [comment]
Ahh yeah, that is what I was looking for!  Okay, make use of your version information, added basic logging, added some if/else statements to support a scenario where someone may have deleted the original file already - mostly for testing.  Service only restarts if needed now.

**Comment by massimocandela** [comment]
I'm going to merge this. If you wish to add your name to the contributor list in the AUTHORS file, do it soon so I merge everything at once.

Thanks for your contribution.

**Comment by massimocandela** [comment]
let me know if I can merge

**Comment by jcoeder** [comment]
Okay, this can be merged now.  I had to fix the crontab entry.  

Thanks!!

**Comment by jcoeder** [comment]
Actually, dont merge yet.  Still working through a few odd issues.

**Comment by jcoeder** [comment]
Okay, fixed!  Relative path vs absolute path issues.  This can now be merged if you are good with it.

**Comment by massimocandela** [comment]
Don't worry, I will probably refactor the documentation page a bit more before to merge into master.
Thanks for your contribution

**Comment by dcec** [comment]
have sense to read only a last release without download the file everyday?

for example using:
curl -sI https://github.com/nttgin/BGPalerter/releases/latest | grep -Po 'tag\/v\K(\S+)'

**Pull request merged**
