### PR TITLE
Debian

### PR DESCRIPTION
**Pull request by b4ldr**
This PR contains a Debian folder necessary for installing BGPalerter loosely following Debian guidelines, however there are some aspects of this package which may not be Debian compliment.  specifically we vendor in all node dependencies.

The packaged produced will:
 * create a `bgpalerter` use
 * install systemd file
 * install the binary to `/usr/bin/bgpalert`
 * install dependencies
 * install the example config files to `/etc/bgpalerter/`

### CODE REVIEW

**Comment by massimocandela** [comment]
Hi @b4ldr,

Thanks for this PR!

I'm listing below things that I see missing:
* the new files need to be added to .npmignore, including the debian directory (this is a minor thing, I can take care of it);
* documentation, we need to add an item in the list of ways BGPalerter can be installed;
* clarification about the changelog file, what level of detail do we need? can we automate it and just update the release version from package.json and refer to the github releases page for the changelog?


Thanks!

**Comment by b4ldr** [comment]
@massimocandela

Sorry this fell of my radar

>     * the new files need to be added to .npmignore, including the debian directory (this is a minor thing, I can take care of it);
Done
> 
>     * documentation, we need to add an item in the list of ways BGPalerter can be installed;
Added something can expand

>     * clarification about the changelog file, what level of detail do we need? can we automate it and just update the release version from package.json and refer to the github releases page for the changelog?

I think that the Debian change log is normally meant to indicate changes between the upstream package and the Debian package.  If theses are the same then yuo9 can just add something like


```
$package_name ($version-1) unstable; urgency=medium

  * New upstream version $version

 -- $author_name <$author_email>  $date
```

e.g.
```
node-bgpalerter (2.0.0-1) unstable; urgency=medium

  * New upstream version 2.0.0

 -- John Bond <jbond@wikimedia.org>  Fri, 14 Jan 2022 13:43:04 +0100
```

See the following example, not that most comments refer to changes under the debian directory

**Comment by massimocandela** [comment]
Hi John, thanks for your contribution. I cannot find the items you marked above as done. If you push in the [debian](https://github.com/b4ldr/BGPalerter/tree/debian) branch they should appear here, but I cannot see new commits.

**Comment by b4ldr** [comment]
sorry should be there now

**Comment by massimocandela** [comment]
Hi @b4ldr, I merged this. 

Thanks a lot for your contribution! Let me know if you would like me to add Wikimedia to the friends list.

**Comment by b4ldr** [comment]
> Let me know if you would like me to add Wikimedia to the friends list.

please do, our puppet repo is public so its already public that we use it :)

**Pull request merged**
