### PR TITLE
Create linux-service.md

### PR DESCRIPTION
**Pull request by jcoeder**
Created a simple guide to show how to run BGPAlerter as a Linux service.

### CODE REVIEW

**Comment by massimocandela** [comment]
Thanks for the tutorial, it is really useful.

I took some time to read it and test it before to give you an answer. I think it is perfect.

Three things:
1) The documentation should be linked somewhere. I was thinking from the main doc index (README.md), under `Installation` (after the items already available).
2) The tutorial should be linked inside Installation > Running BGPalerter from Binaries > All steps > Linux. Maybe a sentence like "Additionally, you can set [BGPalerter as a Linux service](docs/linux-service.md)
3) If you would like, you could add yourself to the `collaborator` section in the author file.

**Comment by jcoeder** [comment]
No problem!

Sure, I can make those changes and submit another PR.  

Thank you

**Comment by massimocandela** [comment]
No, just push the changes to your fork/branch and this should pick them up

**Comment by jcoeder** [comment]
Sorry, not great with git yet.  Made the requested changes.  Let me know if there is anything else.  I am fine not being a collaborator at this time.  Maybe I contribute some code.

**Comment by massimocandela** [comment]
As you wish. Thanks for the contribution.

**Pull request merged**
