### PR TITLE
Move config.yml to config.yml.example

### PR DESCRIPTION
**Pull request by arjenz**
Move config.yml to prevent accidental pushing one's config (or
accidental overwriting one's local config with the upstream version)

Add config.yml to .gitignore

### CODE REVIEW

**Comment by arjenz** [comment]
Might be interesting for `prefixes.yml` as well, but currently that doesn't get generated when it's missing.

**Comment by massimocandela** [comment]
> Might be interesting for `prefixes.yml` as well, but currently that doesn't get generated when it's missing.

It does get generated when missing, but it is generated as empty file so it doesn't really create an issue. Anyway, I think it's not a bad idea to do it also for prefixes.

**Comment by arjenz** [comment]
Oh indeed, it creates an empty `prefixes.yml`, and then crashes because it has no prefixes to monitor. `Error: No prefixes to monitor in prefixes.yml`

**Comment by massimocandela** [comment]
Yes, but is the best I can do in that case, because I create for the user the file and I tell the user to populate it (I cannot pre-populate with random prefixes :) ). Anyway, that error is generated on purpose (handled). Maybe I should remove the verbose logs to don't make it look like an unhandled error.

**Comment by arjenz** [comment]
Yeah agreed, it's the best you can do and it's quite clearly stated to the user what the problem is :)

**Pull request merged**
